package com.kimothorick.plashr.ui.theme

import androidx.compose.ui.graphics.Color

/*Light Theme Colors*/
val primaryLight = Color(0xFF000000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFFFFF)
val onPrimaryContainerLight = Color(0xFF575859)
val secondaryLight = Color(0xFF5D5F5F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF000000)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF1F1F1F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF3F3F3F)
val onTertiaryContainerLight = Color(0xFFD5D3D3)
val errorLight = Color(0xFF970000)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFD61C10)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1B1B1B)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFFDDDDDD)
val outlineVariantLight = Color(0xFFC4C7C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303030)
val inverseOnSurfaceLight = Color(0xFFF1F1F1)
val inversePrimaryLight = Color(0xFFC6C6C7)
val surfaceDimLight = Color(0xFFFFFFFF)
val surfaceBrightLight = Color(0xFFF9F9F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF9F9F9)
val surfaceContainerLight = Color(0xFFEEEEEE)
val surfaceContainerHighLight = Color(0xFFE8E8E8)
val surfaceContainerHighestLight = Color(0xFFE2E2E2)


/*Dark Theme Colors*/
val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF2F3131)
val primaryContainerDark = Color(0xFFD4D4D4)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFFFFF)
val onSecondaryDark = Color(0xFF2F3131)
val secondaryContainerDark = Color(0xFFFFFFFF)
val onSecondaryContainerDark = Color(0xFF000000)
val tertiaryDark = Color(0xFFC8C6C6)
val onTertiaryDark = Color(0xFF303030)
val tertiaryContainerDark = Color(0xFF272727)
val onTertiaryContainerDark = Color(0xFFB4B2B2)
val errorDark = Color(0xFFFFB4A8)
val onErrorDark = Color(0xFF690000)
val errorContainerDark = Color(0xFFAF0000)
val onErrorContainerDark = Color(0xFFFFF8F6)
val backgroundDark = Color(0xFF141313)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF131313)
val onSurfaceDark = Color(0xFFE2E2E2)
val surfaceVariantDark = Color(0xFF444748)
val onSurfaceVariantDark = Color(0xFFC4C7C7)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFF444748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E2)
val inverseOnSurfaceDark = Color(0xFF303030)
val inversePrimaryDark = Color(0xFF5D5F5F)
val surfaceDimDark = Color(0xFF131313)
val surfaceBrightDark = Color(0xFF393939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1B1B1B)
val surfaceContainerDark = Color(0xFF1F1F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353535)
